# Generated by Django 4.2.13 on 2024-05-28 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataShow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 5, 28, 7, 13, 27, 725290, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
