# Generated by Django 4.2.13 on 2024-06-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataShow", "0002_message_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadyToSend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("role", models.CharField(max_length=100)),
            ],
        ),
    ]
